In [1]:
import tensorflow as tf
import numpy as np

from sklearn.linear_model import LinearRegression

tf.__version__

'2.7.4'

In [2]:
train_x = np.array([[5], [-10], [9], [0], [4], [2]])
train_y = np.array([17, -28, 29, 2, 14, 8])   # train_y = train_x * 3 + 2
train_x.shape, train_x, train_y, train_y.shape

((6, 1),
 array([[  5],
        [-10],
        [  9],
        [  0],
        [  4],
        [  2]]),
 array([ 17, -28,  29,   2,  14,   8]),
 (6,))

## Linear Regression

In [3]:
lr = LinearRegression()
lr.fit(train_x[:2], train_y[:2])

LinearRegression()

In [4]:
pred_lr = lr.predict(np.array([[1], [3]]))
pred_lr

array([ 5., 11.])

## NN

In [5]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=1, input_shape=(1,)))
model.compile(optimizer="sgd", loss="mse", metrics=["accuracy"])
model.summary()

2022-10-08 22:57:04.823600: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-08 22:57:04.847941: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-08 22:57:04.848117: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-08 22:57:04.849581: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


2022-10-08 22:57:04.850250: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-08 22:57:04.850416: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-08 22:57:04.850559: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-08 22:57:05.304287: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-08 22:57:05.304465: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from S

In [6]:
model.fit(train_x, train_y, epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 475ms/step - loss: 594.8218 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 2ms/step - loss: 38.5225 - accuracy: 0.0000e+00
Epoch 3/200
1/1 [==============================] - 0s 3ms/step - loss: 4.9868 - accuracy: 0.0000e+00
Epoch 4/200
1/1 [==============================] - 0s 2ms/step - loss: 2.8735 - accuracy: 0.0000e+00
Epoch 5/200
1/1 [==============================] - 0s 2ms/step - loss: 2.6522 - accuracy: 0.0000e+00
Epoch 6/200
1/1 [==============================] - 0s 2ms/step - loss: 2.5480 - accuracy: 0.0000e+00
Epoch 7/200
1/1 [==============================] - 0s 2ms/step - loss: 2.4543 - accuracy: 0.0000e+00
Epoch 8/200
1/1 [==============================] - 0s 2ms/step - loss: 2.3643 - accuracy: 0.0000e+00
Epoch 9/200
1/1 [==============================] - 0s 2ms/step - loss: 2.2777 - accuracy: 0.0000e+00
Epoch 10/200
1/1 [==============================] - 0s 2ms/step - loss: 2.1943 - accur

In [7]:
pred_y = model.predict(np.array([[1],[3]]))

In [8]:
pred_y

array([[ 4.958393],
       [10.962347]], dtype=float32)