In [7]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.7.4'

In [8]:
train_x = np.array([[5], [-10], [9], [0], [4], [2]])
train_y = np.array([17, -28, 29, 2, 14, 8])
train_x.shape, train_x, train_y, train_y.shape

((6, 1),
 array([[  5],
        [-10],
        [  9],
        [  0],
        [  4],
        [  2]]),
 array([ 17, -28,  29,   2,  14,   8]),
 (6,))

In [9]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=1, input_shape=(1,)))
model.compile(optimizer="sgd", loss="mse", metrics=["accuracy"])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.fit(train_x, train_y, epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 171ms/step - loss: 223.9060 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 3ms/step - loss: 16.4471 - accuracy: 0.0000e+00
Epoch 3/200
1/1 [==============================] - 0s 2ms/step - loss: 3.8691 - accuracy: 0.0000e+00
Epoch 4/200
1/1 [==============================] - 0s 3ms/step - loss: 3.0076 - accuracy: 0.0000e+00
Epoch 5/200
1/1 [==============================] - 0s 3ms/step - loss: 2.8542 - accuracy: 0.0000e+00
Epoch 6/200
1/1 [==============================] - 0s 2ms/step - loss: 2.7470 - accuracy: 0.0000e+00
Epoch 7/200
1/1 [==============================] - 0s 2ms/step - loss: 2.6462 - accuracy: 0.0000e+00
Epoch 8/200
1/1 [==============================] - 0s 3ms/step - loss: 2.5493 - accuracy: 0.0000e+00
Epoch 9/200
1/1 [==============================] - 0s 2ms/step - loss: 2.4559 - accuracy: 0.0000e+00
Epoch 10/200
1/1 [==============================] - 0s 2ms/step - loss: 2.3659 - accur

In [11]:
pred_y = model.predict(np.array([[1],[3]]))

In [12]:
pred_y

array([[ 4.9567957],
       [10.960901 ]], dtype=float32)